# Generated by Django 5.1.5 on 2025-01-26 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_of_things', '0003_tags_device_device_type_device_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLogField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('int', 'Int'), ('datetime', 'Datetime'), ('float', 'Float')], default='string', max_length=50)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_of_things.device')),
            ],
        ),
    ]
