# Generated by Django 5.1.5 on 2025-01-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_of_things', '0004_devicelogfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogfield',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicelogfield',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Int'), ('datetime', 'Datetime'), ('float', 'Float'), ('bool', 'Bool')], default='string', max_length=50),
        ),
    ]
