# Generated by Django 5.1.5 on 2025-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_of_things', '0005_devicelogfield_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
