# Generated by Django 5.1.5 on 2025-04-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_of_things', '0006_alter_device_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
